-- MySQL Script generated by MySQL Workbench
-- Wed Dec 29 19:16:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tts` DEFAULT CHARACTER SET utf8 ;
USE `tts` ;

-- -----------------------------------------------------
-- Table `tts`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tts`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(80) NOT NULL,
  `lname` VARCHAR(80) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `entreprise` TINYINT NOT NULL DEFAULT 0,
  `entname` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tts`.`Party`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tts`.`Party` (
  `idParty` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(255) NOT NULL,
  `Description` LONGTEXT NOT NULL,
  `Date` DATE NOT NULL,
  `Ville` VARCHAR(255) NOT NULL,
  `Adresse` VARCHAR(255) NOT NULL,
  `Département` VARCHAR(255) NOT NULL,
  `Ouvert` TINYINT NOT NULL,
  `creatorId` INT NOT NULL,
  `Partycol` VARCHAR(45) NULL,
  PRIMARY KEY (`idParty`),
  INDEX `fk_Party_users1_idx` (`creatorId` ASC) ,
  CONSTRAINT `fk_Party_users1`
    FOREIGN KEY (`creatorId`)
    REFERENCES `tts`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tts`.`PartyJoin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tts`.`PartyJoin` (
  `idPartyJoin` INT NOT NULL AUTO_INCREMENT,
  `Id_user` INT NOT NULL,
  `Id_party` INT NOT NULL,
  `Accepted` TINYINT NOT NULL DEFAULT 0,
  `Fav` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idPartyJoin`),
  INDEX `fk_PartyJoin_users_idx` (`Id_user` ASC),
  INDEX `fk_PartyJoin_Party1_idx` (`Id_party` ASC),
  CONSTRAINT `fk_PartyJoin_users`
    FOREIGN KEY (`Id_user`)
    REFERENCES `tts`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PartyJoin_Party1`
    FOREIGN KEY (`Id_party`)
    REFERENCES `tts`.`Party` (`idParty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tts`.`Fourniture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tts`.`Fourniture` (
  `idFourniture` INT NOT NULL,
  `user` INT NOT NULL,
  `party` INT NOT NULL,
  `Contenu` TEXT NOT NULL,
  PRIMARY KEY (`idFourniture`),
  INDEX `fk_Fourniture_users1_idx` (`user` ASC),
  INDEX `fk_Fourniture_Party1_idx` (`party` ASC),
  CONSTRAINT `fk_Fourniture_users1`
    FOREIGN KEY (`user`)
    REFERENCES `tts`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fourniture_Party1`
    FOREIGN KEY (`party`)
    REFERENCES `tts`.`Party` (`idParty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `tts`.`Favs` (
  `idFavs` INT NOT NULL AUTO_INCREMENT,
  `fav` TINYINT NOT NULL,
  `userId` INT NOT NULL,
  `partyId` INT NOT NULL,
  PRIMARY KEY (`idFavs`),
  INDEX `fk_Favs_Party1_idx` (`partyId` ASC),
  INDEX `fk_Favs_users1_idx` (`userId` ASC),
  CONSTRAINT `fk_Favs_Party1`
    FOREIGN KEY (`partyId`)
    REFERENCES `tts`.`Party` (`idParty`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favs_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `tts`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
